In [9]:
import numpy as np

def blue_color_pick(nb):
    start = np.array([170, 200, 230])
    end = [30, 60, 90]
    spread = start[0] - end[0]
    interval_size = spread/nb
    colors = []
    for i in range(nb):
        colors.append(start - (i+1)*interval_size)

    return colors

In [10]:
blue_color_pick(8)

[array([152.5, 182.5, 212.5]),
 array([135., 165., 195.]),
 array([117.5, 147.5, 177.5]),
 array([100., 130., 160.]),
 array([ 82.5, 112.5, 142.5]),
 array([ 65.,  95., 125.]),
 array([ 47.5,  77.5, 107.5]),
 array([30., 60., 90.])]